server.port=9901
#等待打印结果尝试次数 90次*2秒
wait.result.tryCount=90
print.record.path=C:\\print\\print_recode\\%s\\%s\\%s.png
#模板配置
template.config={"4":{"photo":{"x":120,"y":262,"width":424,"height":424,"roundCorner":424},"userName":{"x":244,"y":729,"style":0,"size":58,"font":"思源宋体 Heavy","color":"0,0,0"},"userId":{"x":235,"y":806,"style":0,"size":37,"font":"思源宋体 Heavy","color":"0,0,0"},"deptName":{"x":204,"y":889,"style":0,"size":46,"font":"思源宋体 Heavy","color":"0,0,0"},"deptName2":{"x":204,"y":957,"style":0,"size":46,"font":"思源宋体 Heavy","color":"0,0,0"},"foregroundImage":"IF.png","backgroundImage":"IB.png"},"5":{"photo":{"x":170,"y":254,"width":326,"height":396,"roundCorner":60},"userName":{"x":244,"y":712,"style":0,"size":58,"font":"思源宋体 Heavy","color":"255,255,255"},"userId":{"x":223,"y":795,"style":0,"size":37,"font":"思源宋体 Heavy","color":"255,255,255"},"deptName":{"x":181,"y":888,"style":0,"size":46,"font":"思源宋体 Heavy","color":"255,255,255"},"deptName2":{"x":204,"y":947,"style":0,"size":46,"font":"思源宋体 Heavy","color":"255,255,255"},"foregroundImage":"OF.png","backgroundImage":"OB.png"},"6":{"photo":{"x":170,"y":254,"width":326,"height":396,"roundCorner":60},"userName":{"x":244,"y":712,"style":0,"size":58,"font":"思源宋体 Heavy","color":"0,0,0"},"userId":{"x":223,"y":795,"style":0,"size":37,"font":"思源宋体 Heavy","color":"0,0,0"},"deptName":{"x":181,"y":888,"style":0,"size":46,"font":"思源宋体 Heavy","color":"0,0,0"},"deptName2":{"x":204,"y":947,"style":0,"size":46,"font":"思源宋体 Heavy","color":"0,0,0"},"foregroundImage":"HAF.png","backgroundImage":"HAB.png"}}
#异常信息映射
error.mapping={"Preheating":"正在预热","Initializing":"正在初始化","No card in printer or the hopper tray is not closed":"打印机中没有卡或料斗托盘未关闭","mark on retransfer film could not be detected":"无法检测到再转印膜上的标记","Card Jam (card was not detected by card supply sensor)":"卡堵塞（供卡传感器未检测到卡）"}
#是否调用打印机接口-打印卡片
isPrint=false
#是否调用打印机接口-检测打印机状态
isCheckStatus=false
isCheckParams=false


core.pool.size=10
max_pool.size=50
queue.capacity=0
keep.alive.seconds=60
thread.name.prefix=Async-